<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Models\School;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Hash;
use Inertia\Inertia;
use App\Services\StudentCardsPdfService;


class StudentController extends Controller
{
    public function index(Request $request)
    {
        $perPage = (int) $request->input('per_page', 10);
        $search = trim((string) $request->input('search', ''));

        $students = User::where('role', 'student')
            ->with('university', 'major', 'school')
            ->withCount('attempts as total_exams')
            ->when($search !== '', function ($query) use ($search) {
                $query->where(function ($query) use ($search) {
                    $query->where('name', 'like', "%{$search}%")
                        ->orWhere('email', 'like', "%{$search}%")
                        ->orWhereHas('school', function ($q) use ($search) {
                            $q->where('name', 'like', "%{$search}%");
                        });
                });
            })
            ->paginate($perPage)
            ->withQueryString();

        return Inertia::render('admin/students/StudentIndex', [
            'students' => $students,
            'filters' => [
                'search' => $search,
            ],
        ]);
    }

    public function create()
    {
        return Inertia::render('admin/students/StudentCreate', [
            'schools' => School::all(),
        ]);
    }

    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'nullable|email|max:255',
            'password' => 'required|string|min:8',
            'school_id' => 'nullable|exists:schools,id',
            'class' => 'required|string|max:255',
        ]);

        $autoGeneratedEmail = false;
        if (empty($validated['email'])) {
            $validated['email'] = $this->generateUniqueStudentEmail($validated['name']);
            $autoGeneratedEmail = true;
        }

        if (User::where('email', $validated['email'])->exists()) {
            return back()->withErrors(['email' => 'Email already exists']);
        }

        $validated['password'] = Hash::make($validated['password']);
        $validated['role'] = 'student';

        User::create($validated);

        $message = $autoGeneratedEmail
            ? "Student created successfully. Auto email: {$validated['email']}"
            : 'Student created successfully';

        return redirect()->route('admin.students.index')
            ->with('success', $message);
    }

    public function show(User $student)
    {
        if ($student->role !== 'student') {
            abort(404);
        }

        $attempts = $student->attempts()
            ->with('exam')
            ->orderByDesc('completed_at')
            ->get()
            ->map(function ($attempt) use ($student) {
                // Use irt_block_score (skor_utbk_pct) if processed
                $skorUtbkPct = $attempt->irt_block_score;

                // Passing grade from university_selections JSON, fallback to major
                $selections   = $student->university_selections ?? [];
                $firstMajorId = $selections[0]['majors'][0] ?? null;
                $passingScore = $firstMajorId
                    ? (\App\Models\Major::find($firstMajorId)?->minimum_passing_grade ?? 0)
                    : ($student->major?->minimum_passing_grade ?? 0);

                $effectiveScore = $skorUtbkPct ?? $attempt->score ?? 0;
                $isPassed       = $attempt->status === 'submitted'
                    ? $effectiveScore >= $passingScore
                    : null; // null = not submitted yet

                return [
                    'id'            => $attempt->id,
                    'status'        => $attempt->status,
                    'skor_utbk_pct' => $skorUtbkPct !== null ? round($skorUtbkPct, 2) : null,
                    'irt_processed' => $skorUtbkPct !== null,
                    'passing_score' => $passingScore,
                    'is_passed'     => $isPassed,
                    'started_at'    => optional($attempt->started_at)->toIso8601String(),
                    'completed_at'  => optional($attempt->completed_at)->toIso8601String(),
                    'exam' => [
                        'id'   => $attempt->exam->id,
                        'name' => $attempt->exam->name,
                    ],
                ];
            });

        return Inertia::render('admin/students/StudentShow', [
            'student' => $student->load('university', 'major', 'school'),
            'exam_attempts' => $attempts,
        ]);
    }

    public function edit(User $student)
    {
        if ($student->role !== 'student') {
            abort(404);
        }

        return Inertia::render('admin/students/StudentEdit', [
            'student' => $student,
            'schools' => School::all(),
        ]);
    }

    public function update(Request $request, User $student)
    {
        if ($student->role !== 'student') {
            abort(404);
        }

        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,email,' . $student->id,
            'school_id' => 'nullable|exists:schools,id',
            'class' => 'nullable|string|max:255',
        ]);

        if ($request->filled('password')) {
            $validated['password'] = Hash::make($request->password);
        }

        $student->update($validated);

        return redirect()->route('admin.students.index')
            ->with('success', 'Student updated successfully');
    }

    private function generateUniqueStudentEmail(string $name): string
    {
        $domain = config('app.student_email_domain', 'students.local');
        $base = Str::slug($name, '.');

        if ($base === '') {
            $base = 'student';
        }

        $candidate = "{$base}@{$domain}";
        $suffix = 1;

        while (User::where('email', $candidate)->exists()) {
            $candidate = "{$base}{$suffix}@{$domain}";
            $suffix++;

            if ($suffix > 9999) {
                $candidate = "{$base}." . Str::lower(Str::random(6)) . "@{$domain}";
                if (! User::where('email', $candidate)->exists()) {
                    break;
                }
            }
        }

        return $candidate;
    }

    public function destroy(User $student)
    {
        if ($student->role !== 'student') {
            abort(404);
        }

        $student->delete();

        return redirect()->route('admin.students.index')
            ->with('success', 'Student deleted successfully');
    }

    public function bulkDelete(Request $request)
    {
        $ids = $request->input('ids', []);

        if (empty($ids)) {
            return redirect()
                ->route('admin.students.index')
                ->with('info', 'Tidak ada siswa yang dipilih untuk dihapus.');
        }

        User::whereIn('id', $ids)->delete();

        return redirect()
            ->route('admin.students.index')
            ->with('success', 'Siswa terpilih berhasil dihapus.');
    }

    public function bulkResetPassword(Request $request)
    {
        $validated = $request->validate([
            'ids' => 'required|array|min:1',
            'ids.*' => 'integer|exists:users,id',
        ]);

        $ids = $validated['ids'];

        $updated = User::whereIn('id', $ids)
            ->where('role', 'student')
            ->update([
                'password' => Hash::make('password'),
            ]);

        return redirect()
            ->route('admin.students.index')
            ->with('success', "Password reset untuk {$updated} siswa.");
    }


    public function cards()
    {
        $schools = School::with(['students' => function ($q) {
            $q->where('role', 'student')
                ->with('school:id,name')
                ->select([
                    'id',
                    'name',
                    'email',
                    'class',
                    'school_id',
                ])
                ->orderBy('name');
        }])
            ->orderBy('name')
            ->get(['id', 'name']);

        return Inertia::render('admin/students/StudentCards', [
            'schools' => $schools,
        ]);
    }


    public function downloadCards(Request $request)
    {
        $schoolId = $request->query('school_id');

        if (!$schoolId) {
            return back()->withErrors(['error' => 'Pilih sekolah terlebih dahulu']);
        }

        $school = School::with(['students' => function ($q) {
            $q->where('role', 'student')
                ->with('school:id,name')
                ->select([
                    'id',
                    'name',
                    'email',
                    'class',
                    'school_id',
                ])
                ->orderBy('name');
        }])->findOrFail($schoolId);

        $pdfService = new StudentCardsPdfService();
        $pdf = $pdfService->generate($school);

        return $pdf->download('student-cards-' . $school->id . '.pdf');
    }
}
